SELECT
	TBLBORROWER.BORROWERNAME BOOROWER_NAME,
	TBLBORROWER.BORROWERSEX BORROWER_GENDER,
	TBLBORROWER.BORROWERDOB BORROWER_DOB,
	TBLBORROWER.BORROWERADDRESS BORROWER_ADDRESS,
	TBLBORROWER.BORROWERTEL BORROWER_PHONE,
	TBLBORROWER.BORROWEREMAIL BORROWER_MAIL,
	TBLBORROWBOOK.LIBRARIAN_ID,
	TBLLIBRARIAN.LIB_NAME LIBRARIAN_NAME,
	TBLLIBRARIAN.LIB_SEX TBLLIBRARIAN_GEMDER,
	TBLLIBRARIAN.LIB_DOB LIBRARIAN_DOB,
	TBLLIBRARIAN.LIB_ADDRESS LIBRARIAN_ADDRESS,
	TBLLIBRARIAN.LIB_TEL LIBRARIAN_PHONE,
	TBLLIBRARIAN.LIB_EMAIL LIBRARIAN_EMAIL,
	TBLLIBRARIAN."LIB_Photo" LIBRARIAN_PHOTO,
	TBLBORROWBOOK.BORROW_DATE,
	TBLBORROWBOOK.RETURN_DATE,
	TBLBORROWBOOK.DISPOSIT_MONEY,
	TBLBORROWBOOK.STATUS,
	TBLBORROWBOOK.BORROWBOOK_ID,
	TBLBORROWBOOKLINE.LINE_ID,
	TBLBORROWBOOKLINE.BOOK_ID,
	TBLBOOK.BOOKTITLE,
	TBLBOOK.BOOKPAGE,
	TBLBOOK.BOOKTYPE,
	TBLBOOK.PUBLISHDATE,
	TBLBOOK.PUBLISHER,
	TBLBOOK.CATEGORYID CATEGORYID,
	TBLAUTHOR.AUTHORNAME AUTHOR_NAME,
	TBLAUTHOR.NATION AUTHOR_NATION,
	TBLAUTHOR.SKILL AUTHOR_SKILL,
	TBLCATEGORY.CATEGORYNAME As CATEGORY_NAME,
	TBLCATEGORY.CAT_DESC AS CATEGORY_DESCRIPTION
FROM
	TBLBORROWBOOK
	INNER JOIN TBLBORROWBOOKLINE ON TBLBORROWBOOK.BORROWBOOK_ID = TBLBORROWBOOKLINE.REF_ID
	RIGHT JOIN TBLLIBRARIAN ON TBLBORROWBOOK.LIBRARIAN_ID = TBLLIBRARIAN.LIB_ID
	RIGHT JOIN TBLBORROWER ON TBLBORROWBOOK.BORROWER_ID = TBLBORROWER.BORROWERID
	INNER JOIN TBLBOOK ON TBLBORROWBOOKLINE.BOOK_ID = TBLBOOK.BOOKID
	RIGHT JOIN AUTHOR_BOOK ON TBLBOOK.BOOKID = AUTHOR_BOOK.BOOKID
	INNER JOIN TBLAUTHOR ON AUTHOR_BOOK.AUTHORID = TBLAUTHOR.AUTHORID
	INNER JOIN TBLCATEGORY ON TBLBOOK.CATEGORYID = TBLCATEGORY.CATEGORYID